### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [react-native-masked-view/masked-view#162]
See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by unfernandito** [comment]
Hi @tom-sherman 

I'm working in this support https://github.com/react-native-masked-view/masked-view/pull/164

**Comment by unfernandito** [comment]
@tom-sherman currently, fabric for android is full working, you can try my fork if you want.

iOS Fabric is barely supported in my fork, not crash but right now I'm stuck with this issue when you try to use the lib:

![image](https://user-images.githubusercontent.com/6326186/177648639-2c47cbf2-cb24-4619-ab27-bc9e762f7fc8.png)

I guess the issue is in the UIManager and how it works under fabric architecture but I'm pretty lost, I'll continue searching for a solution

**Comment by hansdesmedt** [comment]
I started a new discussion about this issue 

https://github.com/reactwg/react-native-new-architecture/discussions/80

**Comment by hansdesmedt** [comment]
hey @unfernandito I created a PR on your PR, can you check and merge both into this lib? Thx!

issues fixed:
- fix build for android
- fix masked view for iOS fabric build

https://github.com/unfernandito/masked-view/pull/3

**Comment by hansdesmedt** [comment]
or I can create a PR with the changes of @unfernandito and mine directly into this repo?

**Comment by unfernandito** [comment]
Hey, yes i Will check your pr
